server:
  port: 9898

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DebojyotiDuttaRoy/Spring_Boot_Microservices_Server_Config
          skipSslValidation: true